import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const sansFont = Funnel_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${sansFont.variable} antialiased font-sans tracking-tighter`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
